import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import { Navbar1 } from "@/components/navbar1";
import { Footer2 } from "@/components/footer2";
import { CursorProvider } from "@/components/CursorProvider";
import CustomCursor from "@/components/CustomCursor";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ECRS | Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Navbar with padding */}
        <Navbar1 />
        <div className="w-full px-4 md:px-8 lg:px-16"></div>

        {/* ✅ Main content without forced padding */}
        <CursorProvider>
          {/* 👇 Add this line */}
          <CustomCursor />
          {/* Main content */}
          <main className="flex-grow w-full">{children}</main>
        </CursorProvider>

        {/* ✅ Footer with padding */}
        <footer className="w-full">
          <div className="pt-10">
            <Footer2 />
          </div>
        </footer>
      </body>
    </html>
  );
}
